services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    cap_add: [NET_ADMIN]
    privileged: true
    networks:
      labnet:
        ipv4_address: 10.9.0.1
  emisor:
    build: .
    command: ["tail", "-f", "/dev/null"]
    cap_add: [NET_ADMIN, NET_RAW]
    privileged: true
    entrypoint: ["/bin/sh", "/entrypoint-host.sh"]
    volumes:
      - ./entrypoint-host.sh:/entrypoint-host.sh:ro
    depends_on:
      - gateway
    networks:
      labnet:
        ipv4_address: 10.9.0.101
  receptor:
    build: .
    command: ["tail", "-f", "/dev/null"]
    cap_add: [NET_ADMIN, NET_RAW]
    privileged: true
    entrypoint: ["/bin/sh", "/entrypoint-host.sh"]
    volumes:
      - ./entrypoint-host.sh:/entrypoint-host.sh:ro
    depends_on:
      - gateway
    networks:
      labnet:
        ipv4_address: 10.9.0.102

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
          gateway: 10.9.0.254
