services:
  atacante:
    build: .
    cap_add: [NET_ADMIN, NET_RAW]
    networks:
      labnet:
        ipv4_address: 10.9.0.10
  victima:
    build: .
    cap_add: [NET_ADMIN, NET_RAW]
    networks:
      labnet:
        ipv4_address: 10.9.0.20
  servidor:
    build: .
    ports:
      - "8080:8080"
    networks:
      labnet:
        ipv4_address: 10.9.0.30

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
